/**
 * 内置词库生成脚本
 * 运行：node generate.js
 * 生成：elementary.json / middle.json / high.json / cet4.json / cet6.json
 */
const fs = require('fs');
const path = __dirname;

// ========== 小学词汇 ~500 ==========
const elementary = [
  ["a","一个"], ["able","能够"], ["about","关于"], ["above","在…上面"], ["accept","接受"],
  ["across","穿过"], ["act","行动"], ["active","积极的"], ["add","添加"], ["afraid","害怕的"],
  ["after","在…之后"], ["afternoon","下午"], ["again","再次"], ["ago","以前"], ["agree","同意"],
  ["air","空气"], ["all","全部"], ["also","也"], ["always","总是"], ["am","是"],
  ["and","和"], ["angry","生气的"], ["animal","动物"], ["answer","回答"], ["ant","蚂蚁"],
  ["any","任何"], ["apple","苹果"], ["are","是"], ["arm","手臂"], ["around","周围"],
  ["arrive","到达"], ["art","艺术"], ["as","作为"], ["ask","问"], ["at","在"],
  ["aunt","阿姨"], ["autumn","秋天"], ["away","离开"], ["baby","婴儿"], ["back","后面"],
  ["bad","坏的"], ["bag","包"], ["ball","球"], ["banana","香蕉"], ["baseball","棒球"],
  ["basketball","篮球"], ["be","是"], ["bear","熊"], ["beautiful","美丽的"], ["because","因为"],
  ["become","成为"], ["bed","床"], ["bedroom","卧室"], ["before","在…之前"], ["begin","开始"],
  ["behind","在…后面"], ["believe","相信"], ["bell","铃"], ["below","在…下面"], ["beside","在…旁边"],
  ["best","最好的"], ["better","更好的"], ["between","在…之间"], ["big","大的"], ["bird","鸟"],
  ["birthday","生日"], ["black","黑色的"], ["blue","蓝色的"], ["boat","船"], ["body","身体"],
  ["book","书"], ["both","两者都"], ["bottle","瓶子"], ["box","盒子"], ["boy","男孩"],
  ["bread","面包"], ["break","打破"], ["breakfast","早餐"], ["bridge","桥"], ["bring","带来"],
  ["brother","兄弟"], ["brown","棕色的"], ["brush","刷子"], ["build","建造"], ["bus","公共汽车"],
  ["busy","忙碌的"], ["but","但是"], ["buy","买"], ["by","通过"], ["cake","蛋糕"],
  ["call","打电话"], ["candle","蜡烛"], ["cap","帽子"], ["car","汽车"], ["card","卡片"],
  ["care","关心"], ["careful","小心的"], ["carry","搬运"], ["cat","猫"], ["catch","抓住"],
  ["chair","椅子"], ["chance","机会"], ["change","改变"], ["cheap","便宜的"], ["cheese","奶酪"],
  ["chicken","鸡肉"], ["child","孩子"], ["children","孩子们"], ["China","中国"], ["Chinese","中文"],
  ["chocolate","巧克力"], ["choose","选择"], ["Christmas","圣诞节"], ["church","教堂"], ["city","城市"],
  ["class","班级"], ["classroom","教室"], ["clean","干净的"], ["clever","聪明的"], ["climb","爬"],
  ["clock","时钟"], ["close","关闭"], ["cloudy","多云的"], ["coat","外套"], ["coffee","咖啡"],
  ["cold","冷的"], ["collect","收集"], ["colour","颜色"], ["come","来"], ["computer","电脑"],
  ["cook","烹饪"], ["cool","凉爽的"], ["cousin","表兄弟"], ["cow","奶牛"], ["crayon","蜡笔"],
  ["cry","哭"], ["cup","杯子"], ["cut","切"], ["dance","跳舞"], ["dark","黑暗的"],
  ["daughter","女儿"], ["day","天"], ["dear","亲爱的"], ["December","十二月"], ["decide","决定"],
  ["deep","深的"], ["delicious","美味的"], ["desk","书桌"], ["dictionary","词典"], ["die","死亡"],
  ["different","不同的"], ["difficult","困难的"], ["dig","挖"], ["dinner","晚餐"], ["dirty","脏的"],
  ["do","做"], ["doctor","医生"], ["dog","狗"], ["doll","洋娃娃"], ["door","门"],
  ["down","向下"], ["draw","画"], ["dream","梦想"], ["dress","连衣裙"], ["drink","喝"],
  ["drive","驾驶"], ["drop","掉落"], ["dry","干的"], ["duck","鸭子"], ["dumpling","饺子"],
  ["each","每个"], ["ear","耳朵"], ["early","早的"], ["earth","地球"], ["east","东方"],
  ["easy","容易的"], ["eat","吃"], ["egg","鸡蛋"], ["eight","八"], ["eighteen","十八"],
  ["elephant","大象"], ["eleven","十一"], ["else","其他"], ["empty","空的"], ["end","结束"],
  ["enemy","敌人"], ["energy","能量"], ["engineer","工程师"], ["enjoy","享受"], ["enough","足够"],
  ["enter","进入"], ["eraser","橡皮"], ["evening","晚上"], ["ever","曾经"], ["every","每个"],
  ["everyone","每个人"], ["everything","一切"], ["example","例子"], ["excellent","优秀的"],
  ["excited","兴奋的"], ["exercise","锻炼"], ["expect","期待"], ["expensive","昂贵的"],
  ["eye","眼睛"], ["face","脸"], ["factory","工厂"], ["fall","秋天；掉落"], ["family","家庭"],
  ["fan","扇子；迷"], ["far","远的"], ["farm","农场"], ["fast","快的"], ["fat","胖的"],
  ["father","父亲"], ["favourite","最喜欢的"], ["feel","感觉"], ["festival","节日"], ["field","田野"],
  ["fifteen","十五"], ["fight","打架"], ["fill","填充"], ["find","找到"], ["fine","好的"],
  ["finger","手指"], ["finish","完成"], ["fire","火"], ["first","第一"], ["fish","鱼"],
  ["five","五"], ["floor","地板"], ["flower","花"], ["fly","飞"], ["follow","跟随"],
  ["food","食物"], ["foot","脚"], ["football","足球"], ["for","为了"], ["foreign","外国的"],
  ["forest","森林"], ["forget","忘记"], ["fork","叉子"], ["form","形式"], ["four","四"],
  ["fourteen","十四"], ["fox","狐狸"], ["free","自由的"], ["fresh","新鲜的"], ["Friday","星期五"],
  ["friend","朋友"], ["frog","青蛙"], ["from","从"], ["front","前面"], ["fruit","水果"],
  ["full","满的"], ["fun","有趣的"], ["future","未来"], ["game","游戏"], ["garden","花园"],
  ["gate","大门"], ["get","得到"], ["gift","礼物"], ["giraffe","长颈鹿"], ["girl","女孩"],
  ["give","给"], ["glad","高兴的"], ["glass","玻璃"], ["glove","手套"], ["go","去"],
  ["goat","山羊"], ["good","好的"], ["goodbye","再见"], ["goose","鹅"], ["grandma","奶奶"],
  ["grandpa","爷爷"], ["grandparent","祖父母"], ["grape","葡萄"], ["grass","草"], ["great","伟大的"],
  ["green","绿色的"], ["ground","地面"], ["group","组"], ["grow","生长"], ["guess","猜"],
  ["guest","客人"], ["guitar","吉他"], ["gun","枪"], ["gym","体育馆"], ["habit","习惯"],
  ["hair","头发"], ["half","一半"], ["hand","手"], ["happy","快乐的"], ["hard","困难的；努力地"],
  ["hat","帽子"], ["have","有"], ["he","他"], ["head","头"], ["health","健康"],
  ["hear","听见"], ["heart","心脏"], ["heavy","重的"], ["hello","你好"], ["help","帮助"],
  ["here","这里"], ["hide","躲藏"], ["high","高的"], ["hill","小山"], ["hobby","爱好"],
  ["hold","持有"], ["hole","洞"], ["holiday","假日"], ["home","家"], ["hometown","家乡"],
  ["homework","家庭作业"], ["honest","诚实的"], ["hope","希望"], ["horse","马"], ["hospital","医院"],
  ["hot","热的"], ["hour","小时"], ["house","房子"], ["how","如何"], ["however","然而"],
  ["huge","巨大的"], ["human","人类"], ["hundred","百"], ["hungry","饥饿的"], ["hunt","打猎"],
  ["hurry","匆忙"], ["hurt","受伤"], ["husband","丈夫"], ["I","我"], ["ice","冰淇淋"],
  ["idea","想法"], ["if","如果"], ["important","重要的"], ["in","在…里面"], ["inch","英寸"],
  ["information","信息"], ["insect","昆虫"], ["inside","在…里面"], ["interest","兴趣"],
  ["interesting","有趣的"], ["Internet","互联网"], ["invent","发明"], ["island","岛屿"],
  ["it","它"], ["its","它的"], ["jacket","夹克"], ["jam","果酱"], ["January","一月"],
  ["jeans","牛仔裤"], ["job","工作"], ["join","加入"], ["juice","果汁"], ["July","七月"],
  ["jump","跳"], ["June","六月"], ["just","刚刚"], ["keep","保持"], ["key","钥匙"],
  ["keyboard","键盘"], ["kick","踢"], ["kid","孩子"], ["kill","杀"], ["kind","种类；善良的"],
  ["king","国王"], ["kitchen","厨房"], ["kite","风筝"], ["knee","膝盖"], ["knife","刀"],
  ["knock","敲"], ["know","知道"], ["knowledge","知识"], ["lady","女士"], ["lake","湖"],
  ["lamp","灯"], ["land","土地"], ["language","语言"], ["large","大的"], ["last","最后的"],
  ["late","迟的"], ["laugh","笑"], ["law","法律"], ["lay","放置"], ["lazy","懒惰的"],
  ["lead","领导"], ["leader","领导"], ["leaf","叶子"], ["learn","学习"], ["least","最少的"],
  ["leave","离开"], ["left","左边"], ["leg","腿"], ["lend","借出"], ["length","长度"],
  ["less","更少的"], ["lesson","课"], ["let","让"], ["letter","信；字母"], ["level","水平"],
  ["library","图书馆"], ["lie","躺；说谎"], ["life","生活"], ["light","光；灯"], ["like","喜欢"],
  ["line","线"], ["lion","狮子"], ["lip","嘴唇"], ["list","列表"], ["listen","听"],
  ["little","小的"], ["live","居住；活的"], ["lock","锁"], ["London","伦敦"], ["lonely","孤独的"],
  ["long","长的"], ["look","看"], ["lord","贵族"], ["lose","失去"], ["lot","很多"],
  ["loud","大声的"], ["love","爱"], ["lovely","可爱的"], ["low","低的"], ["luck","运气"],
  ["lucky","幸运的"], ["lunch","午餐"], ["machine","机器"], ["magazine","杂志"], ["magic","魔法的"],
  ["make","制作"], ["man","男人"], ["manager","经理"], ["manner","方式；礼貌"], ["many","许多"],
  ["map","地图"], ["March","三月"], ["market","市场"], ["master","主人；掌握"], ["match","匹配；比赛"],
  ["math","数学"], ["matter","事情"], ["may","可能"], ["maybe","可能"], ["me","我"],
  ["meal","餐"], ["mean","意思"], ["meat","肉"], ["meet","遇见"], ["member","成员"],
  ["memory","记忆"], ["mend","修理"], ["mention","提及"], ["menu","菜单"], ["message","消息"],
  ["meter","米"], ["middle","中间"], ["might","可能"], ["mile","英里"], ["milk","牛奶"],
  ["mind","头脑；介意"], ["mine","我的"], ["minute","分钟"], ["miss","想念；错过"], ["mistake","错误"],
  ["model","模型"], ["modern","现代的"], ["moment","时刻"], ["Monday","星期一"], ["money","钱"],
  ["monkey","猴子"], ["month","月"], ["moon","月亮"], ["more","更多"], ["morning","早上"],
  ["most","大多数"], ["mother","母亲"], ["mountain","山"], ["mouse","老鼠"], ["mouth","嘴"],
  ["move","移动"], ["movie","电影"], ["much","很多"], ["museum","博物馆"], ["music","音乐"],
  ["must","必须"], ["my","我的"], ["name","名字"], ["national","国家的"], ["nature","自然"],
  ["near","附近"], ["nearly","几乎"], ["necessary","必要的"], ["neck","脖子"], ["need","需要"],
  ["never","从不"], ["new","新的"], ["news","新闻"], ["newspaper","报纸"], ["next","下一个"],
  ["nice","好的"], ["night","晚上"], ["nine","九"], ["nineteen","十九"], ["no","不"],
  ["nobody","没有人"], ["nod","点头"], ["noise","噪音"], ["none","没有一个"], ["noon","中午"],
  ["nor","也不"], ["north","北方"], ["nose","鼻子"], ["not","不"], ["note","笔记"],
  ["nothing","没什么"], ["notice","注意"], ["November","十一月"], ["now","现在"], ["number","数字"],
  ["nurse","护士"], ["object","物体；目标"], ["ocean","海洋"], ["o'clock","…点钟"], ["October","十月"],
  ["of","…的"], ["off","离开"], ["offer","提供"], ["office","办公室"], ["officer","军官"],
  ["often","经常"], ["oil","油"], ["old","老的；旧的"], ["on","在…上"], ["once","一次"],
  ["one","一"], ["onion","洋葱"], ["only","仅仅"], ["open","打开"], ["opposite","相反的"],
  ["orange","橙子"], ["order","命令；顺序"], ["other","其他的"], ["ought","应该"], ["out","外面"],
  ["outside","在外面"], ["over","超过；结束"], ["own","自己的"], ["page","页"], ["pain","疼痛"],
  ["paint","油漆"], ["pair","对；双"], ["palace","宫殿"], ["panda","熊猫"], ["paper","纸"],
  ["parent","父母"], ["park","公园"], ["part","部分"], ["party","聚会"], ["pass","通过"],
  ["passenger","乘客"], ["past","过去的"], ["path","小路"], ["pay","支付"], ["peace","和平"],
  ["pear","梨"], ["pen","钢笔"], ["pencil","铅笔"], ["people","人们"], ["perfect","完美的"],
  ["perhaps","或许"], ["period","时期"], ["person","人"], ["phone","电话"], ["photo","照片"],
  ["piano","钢琴"], ["pick","挑选"], ["picture","图片"], ["piece","片；块"], ["pig","猪"],
  ["pill","药丸"], ["pilot","飞行员"], ["pink","粉色的"], ["pity","同情"], ["place","地方"],
  ["plan","计划"], ["plane","飞机"], ["plant","植物"], ["plate","盘子"], ["play","玩；戏剧"],
  ["player","运动员"], ["playground","操场"], ["please","请"], ["pleasure","快乐"], ["plenty","丰富"],
  ["pocket","口袋"], ["poem","诗"], ["point","点；指"], ["police","警察"], ["policy","政策"],
  ["polite","礼貌的"], ["pool","游泳池"], ["poor","贫穷的"], ["popular","流行的"], ["population","人口"],
  ["pork","猪肉"], ["position","位置"], ["possible","可能的"], ["post","邮寄"], ["potato","土豆"],
  ["pound","磅；英镑"], ["practice","练习"], ["praise","表扬"], ["prepare","准备"], ["present","礼物；现在的"],
  ["president","总统"], ["press","按；新闻"], ["pretend","假装"], ["pretty","漂亮的"], ["price","价格"],
  ["prime","主要的"], ["print","打印"], ["prison","监狱"], ["private","私人的"], ["prize","奖品"],
  ["problem","问题"], ["produce","生产"], ["product","产品"], ["program","节目；程序"], ["promise","承诺"],
  ["pronounce","发音"], ["proper","适当的"], ["protect","保护"], ["proud","自豪的"], ["prove","证明"],
  ["provide","提供"], ["public","公共的"], ["pull","拉"], ["pupil","学生"], ["purple","紫色的"],
  ["purpose","目的"], ["push","推"], ["put","放"], ["quarter","四分之一；一刻钟"], ["queen","女王"],
  ["question","问题"], ["quick","快的"], ["quiet","安静的"], ["quite","相当"], ["race","赛跑"],
  ["radio","收音机"], ["rain","雨"], ["raise","举起；提高"], ["rapid","迅速的"], ["rat","老鼠"],
  ["rather","相当"], ["reach","到达"], ["read","读"], ["ready","准备好的"], ["real","真实的"],
  ["realise","意识到"], ["reason","原因"], ["receive","收到"], ["recent","最近的"], ["record","记录"],
  ["red","红色的"], ["refuse","拒绝"], ["regard","看待"], ["regret","后悔"], ["relation","关系"],
  ["relative","亲戚"], ["relax","放松"], ["remain","保持"], ["remember","记住"], ["remove","移走"],
  ["rent","租"], ["repair","修理"], ["repeat","重复"], ["reply","回复"], ["report","报告"],
  ["republic","共和国"], ["request","请求"], ["require","需要"], ["research","研究"], ["resource","资源"],
  ["respect","尊重"], ["rest","休息；剩余"], ["restaurant","餐厅"], ["result","结果"], ["retire","退休"],
  ["return","返回"], ["review","复习；评论"], ["rice","米饭"], ["rich","富有的"], ["ride","骑"],
  ["right","正确的；右边"], ["ring","戒指；铃声"], ["rise","上升"], ["river","河流"], ["road","路"],
  ["rock","岩石"], ["role","角色"], ["roll","滚动"], ["roof","屋顶"], ["room","房间"],
  ["root","根"], ["rope","绳子"], ["rose","玫瑰"], ["round","圆的；周围"], ["row","行；划船"],
  ["rubber","橡胶；橡皮"], ["rubbish","垃圾"], ["rule","规则"], ["ruler","尺子"], ["run","跑"],
  ["rush","冲"], ["sad","悲伤的"], ["safe","安全的"], ["sail","航行"], ["sale","销售"],
  ["salt","盐"], ["same","相同的"], ["sand","沙子"], ["Saturday","星期六"], ["save","拯救；节省"],
  ["say","说"], ["scene","场景"], ["school","学校"], ["science","科学"], ["scientist","科学家"],
  ["score","分数"], ["screen","屏幕"], ["sea","海"], ["search","搜索"], ["season","季节"],
  ["seat","座位"], ["second","第二；秒"], ["secret","秘密的"], ["secretary","秘书"], ["see","看见"],
  ["seed","种子"], ["seem","似乎"], ["seldom","很少"], ["select","选择"], ["self","自己"],
  ["sell","卖"], ["send","发送"], ["sense","感觉"], ["sentence","句子"], ["separate","分开的"],
  ["September","九月"], ["serious","严肃的"], ["servant","仆人"], ["serve","服务"], ["service","服务"],
  ["set","设置"], ["settle","解决"], ["seven","七"], ["several","几个"], ["shake","摇动"],
  ["shall","将要"], ["shame","羞愧"], ["shape","形状"], ["share","分享"], ["she","她"],
  ["sheep","羊"], ["sheet","张；薄片"], ["shelf","架子"], ["shine","照耀"], ["ship","船"],
  ["shirt","衬衫"], ["shoe","鞋"], ["shoot","射击"], ["shop","商店"], ["short","短的；矮的"],
  ["shot","射击"], ["should","应该"], ["shoulder","肩膀"], ["shout","喊叫"], ["show","展示"],
  ["shower","淋浴；阵雨"], ["shut","关闭"], ["shy","害羞的"], ["sick","生病的"], ["side","边"],
  ["sight","视力；景象"], ["sign","标志"], ["silence","沉默"], ["silent","沉默的"], ["silly","愚蠢的"],
  ["silver","银色的"], ["similar","相似的"], ["simple","简单的"], ["since","自从"], ["sing","唱"],
  ["single","单一的"], ["sink","下沉"], ["sir","先生"], ["sister","姐妹"], ["sit","坐"],
  ["situation","情况"], ["six","六"], ["size","尺寸"], ["skill","技能"], ["skin","皮肤"],
  ["skirt","裙子"], ["sky","天空"], ["slave","奴隶"], ["sleep","睡觉"], ["slight","轻微的"],
  ["slip","滑倒"], ["slow","慢的"], ["small","小的"], ["smart","聪明的"], ["smell","闻"],
  ["smile","微笑"], ["smoke","烟；吸烟"], ["smooth","光滑的"], ["snow","雪"], ["so","所以；如此"],
  ["soap","肥皂"], ["soccer","足球"], ["social","社会的"], ["society","社会"], ["sock","袜子"],
  ["soft","柔软的"], ["soil","土壤"], ["soldier","士兵"], ["solid","固体"], ["solution","解决方案"],
  ["solve","解决"], ["some","一些"], ["someone","某人"], ["something","某事"], ["sometimes","有时"],
  ["son","儿子"], ["song","歌曲"], ["soon","很快"], ["sort","种类"], ["soul","灵魂"],
  ["sound","声音"], ["soup","汤"], ["south","南方"], ["space","空间"], ["spare","空闲的"],
  ["speak","说话"], ["special","特别的"], ["speech","演讲"], ["speed","速度"], ["spell","拼写"],
  ["spend","花费"], ["spirit","精神"], ["sport","运动"], ["spot","地点；斑点"], ["spread","传播"],
  ["spring","春天"], ["square","广场；正方形"], ["stage","舞台；阶段"], ["stair","楼梯"],
  ["stamp","邮票"], ["stand","站"], ["standard","标准"], ["star","星星"], ["stare","凝视"],
  ["start","开始"], ["state","状态；国家"], ["station","车站"], ["stay","停留"], ["steal","偷"],
  ["steam","蒸汽"], ["steel","钢铁"], ["step","步骤；脚步"], ["stick","棍子；粘"], ["still","仍然"],
  ["stomach","胃"], ["stone","石头"], ["stop","停止"], ["store","商店；存储"], ["storm","暴风雨"],
  ["story","故事"], ["straight","直的；直接"], ["strange","奇怪的"], ["stranger","陌生人"],
  ["stream","溪流"], ["street","街道"], ["strength","力量"], ["strict","严格的"], ["strike","打；罢工"],
  ["string","线；字符串"], ["strong","强壮的"], ["struggle","斗争；挣扎"], ["student","学生"],
  ["study","学习；研究"], ["stupid","愚蠢的"], ["subject","科目；主题"], ["succeed","成功"],
  ["success","成功"], ["such","这样的"], ["sugar","糖"], ["suggest","建议"], ["suit","适合"],
  ["suitable","合适的"], ["summer","夏天"], ["sun","太阳"], ["Sunday","星期日"], ["sunny","晴朗的"],
  ["sunrise","日出"], ["sunset","日落"], ["super","超级的"], ["supper","晚餐"], ["supply","供应"],
  ["support","支持"], ["suppose","假设"], ["sure","确定的"], ["surface","表面"], ["surprise","惊奇"],
  ["surround","包围"], ["sweep","扫"], ["sweet","甜的；糖果"], ["swim","游泳"], ["table","桌子"],
  ["tail","尾巴"], ["take","拿；花费"], ["tale","故事"], ["talent","天赋"], ["talk","谈话"],
  ["tall","高的"], ["tape","磁带；胶带"], ["task","任务"], ["taste","尝；味道"], ["tax","税"],
  ["taxi","出租车"], ["tea","茶"], ["teach","教"], ["teacher","老师"], ["team","团队"],
  ["tear","眼泪；撕"], ["telephone","电话"], ["television","电视"], ["tell","告诉"], ["temperature","温度"],
  ["ten","十"], ["tennis","网球"], ["term","学期；术语"], ["terrible","可怕的"], ["test","测试"],
  ["text","课文；文本"], ["than","比"], ["thank","感谢"], ["that","那个"], ["the","这个"],
  ["theatre","剧院"], ["their","他们的"], ["them","他们"], ["themselves","他们自己"], ["then","然后"],
  ["there","那里"], ["these","这些"], ["they","他们"], ["thick","厚的；浓的"], ["thief","小偷"],
  ["thin","瘦的；薄的"], ["thing","东西；事情"], ["think","想；认为"], ["third","第三"], ["thirsty","口渴的"],
  ["thirteen","十三"], ["thirty","三十"], ["this","这个"], ["those","那些"], ["though","虽然"],
  ["thought","思想"], ["thousand","千"], ["thread","线"], ["three","三"], ["through","通过"],
  ["throw","扔"], ["Thursday","星期四"], ["ticket","票"], ["tidy","整洁的"], ["tie","系；领带"],
  ["tiger","老虎"], ["tight","紧的"], ["till","直到"], ["time","时间；次数"], ["tiny","微小的"],
  ["tire","轮胎"], ["tired","疲劳的"], ["to","到"], ["today","今天"], ["together","一起"],
  ["toilet","厕所"], ["tomato","西红柿"], ["tomorrow","明天"], ["tone","语气；色调"], ["tongue","舌头；语言"],
  ["tonight","今晚"], ["too","太；也"], ["tool","工具"], ["tooth","牙齿"], ["top","顶部"],
  ["total","总计"], ["touch","触摸"], ["tour","旅行"], ["tourist","游客"], ["toward","朝向"],
  ["tower","塔"], ["town","城镇"], ["toy","玩具"], ["track","追踪；轨道"], ["trade","贸易"],
  ["tradition","传统"], ["traffic","交通"], ["train","火车；训练"], ["translate","翻译"], ["trash","垃圾"],
  ["travel","旅行"], ["treasure","宝藏"], ["treat","对待；治疗"], ["tree","树"], ["trick","技巧；诡计"],
  ["trip","旅行"], ["trouble","麻烦"], ["truck","卡车"], ["true","真实的"], ["trust","信任"],
  ["truth","真相"], ["try","尝试"], ["T-shirt","T恤"], ["Tuesday","星期二"], ["turn","转动；轮到"],
  ["twelve","十二"], ["twenty","二十"], ["twice","两次"], ["twin","双胞胎"], ["two","二"],
  ["type","类型；打字"], ["ugly","丑陋的"], ["uncle","叔叔"], ["under","在…下面"], ["understand","理解"],
  ["unit","单元；单位"], ["unite","联合"], ["universe","宇宙"], ["university","大学"], ["unknown","未知的"],
  ["unless","除非"], ["unlike","不像"], ["unlucky","不幸的"], ["until","直到"], ["unusual","不寻常的"],
  ["up","向上"], ["upon","在…上"], ["upper","上面的"], ["upset","沮丧的"], ["upstairs","楼上"],
  ["upward","向上的"], ["us","我们"], ["use","使用"], ["used","习惯的；用过的"], ["useful","有用的"],
  ["useless","无用的"], ["usual","通常的"], ["valley","山谷"], ["valuable","有价值的"], ["value","价值"],
  ["various","各种各样的"], ["vegetable","蔬菜"], ["very","非常"], ["victory","胜利"], ["video","视频"],
  ["view","视野；观点"], ["village","村庄"], ["violin","小提琴"], ["visit","访问；参观"], ["voice","声音"],
  ["wait","等待"], ["wake","醒来"], ["walk","走路"], ["wall","墙"], ["want","想要"],
  ["war","战争"], ["warm","温暖的"], ["warn","警告"], ["wash","洗"], ["waste","浪费"],
  ["watch","看；手表"], ["water","水"], ["wave","波浪；挥手"], ["way","方法；路"], ["we","我们"],
  ["weak","弱的"], ["wealth","财富"], ["wear","穿"], ["weather","天气"], ["Wednesday","星期三"],
  ["week","星期"], ["weekend","周末"], ["weigh","称重"], ["weight","重量"], ["welcome","欢迎"],
  ["well","好；井"], ["west","西方"], ["wet","湿的"], ["what","什么"], ["wheat","小麦"],
  ["wheel","轮子"], ["when","什么时候"], ["where","哪里"], ["whether","是否"], ["which","哪个"],
  ["while","当…的时候"], ["whisper","低语"], ["white","白色的"], ["who","谁"], ["whole","整个的"],
  ["whom","谁（宾格）"], ["whose","谁的"], ["why","为什么"], ["wide","宽的"], ["wife","妻子"],
  ["wild","野生的"], ["will","将；意志"], ["willing","愿意的"], ["win","赢"], ["wind","风"],
  ["window","窗户"], ["wine","酒"], ["wing","翅膀"], ["winner","赢家"], ["winter","冬天"],
  ["wise","明智的"], ["wish","希望"], ["with","和…一起"], ["within","在…之内"], ["without","没有"],
  ["wolf","狼"], ["woman","女人"], ["wonder","想知道"], ["wonderful","精彩的"], ["wood","木头"],
  ["wooden","木制的"], ["wool","羊毛"], ["word","单词"], ["work","工作"], ["worker","工人"],
  ["world","世界"], ["worry","担心"], ["worse","更坏的"], ["worst","最坏的"], ["worth","值得的"],
  ["would","将会"], ["wound","伤口"], ["wrap","包裹"], ["write","写"], ["wrong","错误的"],
  ["yard","院子"], ["year","年"], ["yellow","黄色的"], ["yes","是的"], ["yesterday","昨天"],
  ["yet","还；然而"], ["you","你"], ["young","年轻的"], ["your","你的"], ["yourself","你自己"],
  ["youth","青春"], ["zero","零"], ["zoo","动物园"]
];
const ELEM_MAP = elementary.map(([en, zh]) => ({ english: en, chinese: zh }));

// ========== 初中词汇 = elementary + 新词 ~1500 ==========
const middleExtra = [
  ["ability","能力"], ["absence","缺席"], ["absent","缺席的"], ["absorb","吸收"],
  ["abstract","抽象的"], ["accent","口音"], ["accident","事故"], ["account","账户；描述"],
  ["accurate","准确的"], ["accuse","控告"], ["achieve","实现；达到"], ["acknowledge","承认"],
  ["acquire","获得"], ["adapt","适应"], ["addition","加法；增加"], ["address","地址"],
  ["adjust","调整"], ["admire","钦佩"], ["admit","承认"], ["adopt","采纳；收养"],
  ["adult","成年人"], ["advance","前进；进步"], ["advantage","优势"], ["adventure","冒险"],
  ["advertise","做广告"], ["advice","建议"], ["advise","建议"], ["affair","事务"],
  ["affect","影响"], ["afford","负担得起"], ["agriculture","农业"], ["ahead","在前面"],
  ["aid","帮助；援助"], ["aim","目标"], ["aircraft","飞机"], ["airline","航空公司"],
  ["alarm","警报"], ["album","相册"], ["alcohol","酒精"], ["allow","允许"],
  ["although","尽管"], ["altogether","总共"], ["announce","宣布"], ["anxiety","焦虑"],
  ["anxious","焦虑的"], ["anyhow","无论如何"], ["anywhere","任何地方"], ["apart","分开"],
  ["apologize","道歉"], ["appearance","出现；外貌"], ["appetite","胃口"], ["applaud","鼓掌"],
  ["appoint","任命"], ["appreciate","感激；欣赏"], ["approach","接近；方法"], ["approve","批准"],
  ["argue","争论"], ["argument","争论"], ["arrangement","安排"], ["arrest","逮捕"],
  ["article","文章"], ["ash","灰"], ["ashamed","羞愧的"], ["aside","在旁边"],
  ["aspect","方面"], ["assist","协助"], ["assistant","助理"], ["assume","假设"],
  ["astonish","使惊讶"], ["atmosphere","气氛；大气"], ["attach","附上"], ["attempt","尝试"],
  ["attend","参加"], ["attention","注意力"], ["attitude","态度"], ["attract","吸引"],
  ["attractive","有吸引力的"], ["audience","观众"], ["author","作者"], ["authority","权威"],
  ["automatic","自动的"], ["available","可用的"], ["average","平均的"], ["avoid","避免"],
  ["award","奖品"], ["aware","意识到"], ["balance","平衡"], ["bar","酒吧；条；杆"],
  ["bare","赤裸的"], ["bargain","讨价还价"], ["barrier","障碍"], ["base","基础；基地"],
  ["basic","基本的"], ["basin","盆"], ["basis","基础"], ["battle","战斗"],
  ["beach","海滩"], ["bean","豆"], ["beard","胡须"], ["beast","野兽"],
  ["beat","打；打败"], ["beauty","美丽"], ["bee","蜜蜂"], ["beef","牛肉"],
  ["beg","乞求"], ["behave","表现"], ["behavior","行为"], ["being","存在；生命"],
  ["bend","弯曲"], ["beneath","在…之下"], ["benefit","利益；受益"], ["besides","此外"],
  ["bet","打赌"], ["bible","圣经"], ["billion","十亿"], ["biology","生物学"],
  ["birth","出生"], ["biscuit","饼干"], ["bite","咬"], ["bitter","苦的"],
  ["blame","责备"], ["blank","空白的"], ["blanket","毯子"], ["bleed","流血"],
  ["bless","祝福"], ["blind","盲的"], ["block","块；街区；阻止"], ["blood","血"],
  ["blouse","女衬衫"], ["blow","吹"], ["board","板；董事会"], ["boast","吹嘘"],
  ["bomb","炸弹"], ["bone","骨头"], ["boot","靴子"], ["border","边界"],
  ["bore","使厌烦"], ["boring","无聊的"], ["born","出生的"], ["borrow","借入"],
  ["boss","老板"], ["bottom","底部"], ["bound","受约束的；必然"], ["bow","鞠躬；弓"],
  ["bowl","碗"], ["brain","大脑"], ["branch","分支"], ["brand","品牌"],
  ["brave","勇敢的"], ["breath","呼吸"], ["breathe","呼吸"], ["breed","繁殖"],
  ["brick","砖"], ["brief","简短的"], ["bright","明亮的"], ["broad","宽的"],
  ["broadcast","广播"], ["broom","扫帚"], ["bubble","气泡"], ["bucket","桶"],
  ["budget","预算"], ["bunch","束；串"], ["burden","负担"], ["burglar","窃贼"],
  ["burn","燃烧"], ["burst","爆发"], ["bury","埋葬"], ["bush","灌木"],
  ["butter","黄油"], ["butterfly","蝴蝶"], ["button","按钮"]
];

const middle = [...ELEM_MAP, ...middleExtra.map(([en,zh])=>({english:en,chinese:zh}))];

// ========== 高中词汇 ~2000 ==========
const highExtra = [
  ["abandon","放弃"], ["abolish","废除"], ["abortion","流产"], ["abroad","在国外"],
  ["abrupt","突然的"], ["absence","缺席"], ["absolute","绝对的"], ["abuse","滥用"],
  ["academic","学术的"], ["accelerate","加速"], ["access","通道；访问"], ["accompany","陪伴"],
  ["accomplish","完成"], ["accountant","会计师"], ["accumulate","积累"], ["acid","酸的；酸"],
  ["acquaintance","熟人"], ["acquisition","获得"], ["acre","英亩"], ["activate","激活"],
  ["acute","急性的；敏锐的"], ["adequate","足够的"], ["adjust","调整"], ["administration","管理"],
  ["admirable","令人钦佩的"], ["adolescent","青少年"], ["adore","崇拜；喜爱"],
  ["adverse","不利的"], ["advocate","提倡"], ["affection","感情"], ["agency","代理处"],
  ["agenda","议程"], ["aggressive","侵略的；有进取心的"], ["agony","痛苦"], ["agreeable","宜人的"],
  ["alcohol","酒精"], ["alert","警觉的"], ["algebra","代数"], ["alien","外国的；外星人"],
  ["allege","断言"], ["alley","小巷"], ["allocate","分配"], ["allowance","津贴；零花钱"],
  ["ally","盟友"], ["alongside","在旁边"], ["alter","改变"], ["alternative","替代的"],
  ["altitude","海拔"], ["aluminium","铝"], ["amateur","业余爱好者"], ["amaze","使惊奇"],
  ["ambiguous","模棱两可的"], ["ambition","雄心"], ["ambitious","有雄心的"], ["ambulance","救护车"],
  ["amid","在…中"], ["amount","数量"], ["ample","充足的"], ["amuse","逗乐"],
  ["analyse","分析"], ["analysis","分析"], ["ancestor","祖先"], ["anchor","锚"],
  ["anecdote","轶事"], ["angle","角度"], ["ankle","脚踝"], ["anniversary","周年纪念"],
  ["annoy","使烦恼"], ["annual","年度的"], ["anticipate","预期"], ["antique","古董"],
  ["anxiety","焦虑"], ["anyway","不管怎样"], ["apart","分开"], ["apartment","公寓"],
  ["apparent","明显的"], ["appeal","呼吁；吸引"], ["appetite","食欲"], ["appliance","电器"],
  ["applicant","申请人"], ["application","申请；应用"], ["appoint","任命"], ["appointment","约会；任命"],
  ["appreciate","欣赏；感激"], ["approach","接近；方法"], ["appropriate","适当的"], ["approval","批准"],
  ["approve","批准"], ["approximately","大约"], ["architecture","建筑"], ["argue","争论"],
  ["arise","出现"], ["arithmetic","算术"], ["arm","手臂"], ["arouse","唤起"],
  ["arrange","安排"], ["arrangement","安排"], ["arrow","箭"], ["artificial","人工的"],
  ["aside","在旁边"], ["aspect","方面"], ["assemble","集合；组装"], ["assembly","集合；议会"],
  ["assess","评估"], ["assessment","评估"], ["assign","分配；指派"], ["assignment","作业；分配"],
  ["assist","协助"], ["assistance","帮助"], ["associate","联想；联系"], ["association","协会；联想"],
  ["assume","假设"], ["assumption","假设"], ["assure","保证"], ["astonish","使惊讶"],
  ["astronaut","宇航员"], ["astronomy","天文学"], ["athlete","运动员"], ["Atlantic","大西洋"],
  ["atom","原子"], ["attach","附上；系"], ["attain","达到"], ["attempt","尝试"],
  ["attend","参加"], ["attendance","出席"], ["attentively","专注地"], ["attitude","态度"],
  ["attract","吸引"], ["attraction","吸引力"], ["attribute","归因于"], ["auction","拍卖"],
  ["audience","观众"], ["authentic","真正的"], ["author","作者"], ["authority","权威"],
  ["automatic","自动的"], ["autonomous","自治的"], ["available","可用的"], ["avenue","大道"],
  ["average","平均的"], ["avoid","避免"], ["await","等待"], ["award","奖品"],
  ["aware","意识到"], ["awful","可怕的"], ["awkward","尴尬的"], ["bachelor","学士；单身汉"],
  ["backward","向后的"], ["bacon","培根"], ["bacterium","细菌"], ["badge","徽章"],
  ["baggage","行李"], ["bakery","面包店"], ["balcony","阳台"], ["ballet","芭蕾"],
  ["ballot","选票"], ["ban","禁止"], ["band","乐队；带子"], ["bandage","绷带"],
  ["bang","巨响；猛击"], ["bankrupt","破产的"], ["banner","横幅"], ["banquet","宴会"],
  ["barber","理发师"], ["barely","几乎不"], ["bargain","讨价还价；便宜货"], ["barn","谷仓"],
  ["barrel","桶"], ["barrier","障碍"], ["basement","地下室"], ["basin","盆"],
  ["basket","篮子"], ["bat","蝙蝠；球拍"], ["bath","洗澡"], ["bathe","洗澡"],
  ["bathroom","浴室"], ["battery","电池"], ["battle","战斗"], ["bay","海湾"],
  ["beach","海滩"], ["beam","横梁；光束"], ["bean","豆"], ["bear","忍受；熊"],
  ["beard","胡须"], ["beast","野兽"], ["beaten","被打败的"], ["beg","乞求"],
  ["beggar","乞丐"], ["behalf","代表"], ["behave","行为"], ["behavior","行为"],
  ["being","存在；生命"], ["belief","信念"], ["belly","肚子"], ["belong","属于"],
  ["beloved","心爱的"], ["belt","腰带"], ["bench","长凳"], ["bend","弯曲"],
  ["beneath","在…之下"], ["beneficial","有益的"], ["benefit","利益；受益"], ["besides","此外"],
  ["betray","背叛"], ["bible","圣经"], ["bid","出价；投标"], ["billion","十亿"],
  ["bind","绑"], ["biography","传记"], ["biology","生物学"], ["biscuit","饼干"],
  ["bishop","主教"], ["bitter","苦的"], ["blackboard","黑板"], ["blade","刀片"],
  ["blank","空白的"], ["blanket","毯子"], ["blast","爆炸"], ["bleed","流血"],
  ["blend","混合"], ["bless","祝福"], ["blind","瞎的"], ["block","块；街区；阻碍"],
  ["blood","血"], ["bloom","开花"], ["blossom","花"], ["blouse","女衬衫"],
  ["blow","吹"], ["blueprint","蓝图"], ["board","板；董事会"], ["boast","吹嘘"],
  ["bold","大胆的"], ["bomb","炸弹"], ["bond","纽带；债券"], ["bone","骨头"],
  ["bonus","奖金"], ["boom","繁荣"], ["boot","靴子"], ["border","边界"],
  ["bore","使厌烦"], ["boring","无聊的"], ["borough","行政区"], ["bosom","胸部；胸怀"],
  ["botany","植物学"], ["bother","打扰"], ["bottom","底部"], ["bounce","弹跳"],
  ["bound","必然的；受约束的"], ["boundary","边界"], ["bow","鞠躬；弓"], ["bowl","碗"],
  ["brain","大脑"], ["brake","刹车"], ["branch","分支"], ["brand","品牌"],
  ["bravery","勇敢"], ["breach","违反；缺口"], ["breadth","宽度"], ["breakthrough","突破"],
  ["breast","胸部"], ["breath","呼吸"], ["breathe","呼吸"], ["breed","繁殖；品种"],
  ["breeze","微风"], ["bribe","贿赂"], ["brick","砖"], ["bride","新娘"],
  ["bridegroom","新郎"], ["brief","简短的"], ["brilliant","灿烂的；杰出的"], ["bring","带来"],
  ["brisk","轻快的"], ["broad","宽的"], ["broadcast","广播"], ["brochure","小册子"],
  ["broken","破碎的"], ["bronze","青铜"], ["brook","小溪"], ["brow","眉毛；额头"],
  ["brown","棕色的"], ["brunch","早午餐"], ["brush","刷子"], ["bubble","气泡"],
  ["bucket","桶"], ["bud","花蕾"], ["Buddhism","佛教"], ["budget","预算"],
  ["buffer","缓冲区"], ["buffet","自助餐"], ["bug","小虫；故障"], ["bulb","灯泡；球茎"],
  ["bulk","大块；大量"], ["bull","公牛"], ["bullet","子弹"], ["bulletin","公告"],
  ["bunch","束；串"], ["burden","负担"], ["bureau","局；办公处"], ["burglar","窃贼"],
  ["burial","葬礼"], ["burn","燃烧"], ["burst","爆发"], ["bury","埋葬"],
  ["bush","灌木"], ["business","生意；事务"], ["butcher","屠夫"], ["butter","黄油"],
  ["butterfly","蝴蝶"], ["button","按钮"], ["cabbage","卷心菜"], ["cabin","小屋"],
  ["cabinet","内阁；橱柜"], ["cable","电缆"], ["cafe","咖啡馆"], ["cage","笼子"],
  ["calculate","计算"], ["calculator","计算器"], ["calendar","日历"], ["calm","平静的"],
  ["camel","骆驼"], ["camera","相机"], ["campaign","运动；战役"], ["campus","校园"],
  ["canal","运河"], ["cancel","取消"], ["candidate","候选人"], ["canteen","食堂"],
  ["capability","能力"], ["capable","有能力的"], ["capacity","容量；能力"], ["capital","首都；资本"],
  ["capsule","胶囊；太空舱"], ["captain","船长；队长"], ["capture","捕获"], ["carbon","碳"],
  ["career","职业"], ["cargo","货物"], ["carpenter","木匠"], ["carpet","地毯"],
  ["carriage","马车；车厢"], ["carrier","运输工具"], ["carrot","胡萝卜"], ["cartoon","卡通"],
  ["carve","雕刻"], ["cash","现金"], ["cashier","收银员"], ["cassette","磁带盒"],
  ["cast","投掷；演员表"], ["castle","城堡"], ["casual","随意的"], ["catalog","目录"],
  ["category","类别"], ["cater","提供饮食；迎合"], ["catholic","天主教的"], ["cattle","牛"],
  ["cause","原因；引起"], ["caution","小心"], ["cautious","小心的"], ["cave","洞穴"],
  ["cease","停止"], ["ceiling","天花板"], ["celebrate","庆祝"], ["celebration","庆祝"],
  ["cell","细胞；牢房"], ["cellar","地窖"], ["cement","水泥"], ["centigrade","摄氏的"],
  ["centimetre","厘米"], ["central","中央的"], ["century","世纪"], ["cereal","谷物"],
  ["ceremony","典礼"], ["certain","确定的"], ["certificate","证书"], ["chain","链条"],
  ["challenge","挑战"], ["champion","冠军"], ["channel","频道；通道"], ["chapter","章"],
  ["character","性格；角色"], ["characteristic","特征"], ["charge","收费；充电；负责"],
  ["charity","慈善"], ["charm","魅力"], ["chart","图表"], ["chase","追逐"],
  ["cheat","欺骗"], ["cheer","欢呼"], ["cheerful","愉快的"], ["chemical","化学的"],
  ["chemist","化学家；药剂师"], ["cheque","支票"], ["cherish","珍惜"], ["cherry","樱桃"],
  ["chess","棋"], ["chest","胸膛；箱子"], ["chew","咀嚼"], ["chief","主要的；首领"],
  ["childhood","童年"], ["chimney","烟囱"], ["chin","下巴"], ["china","瓷器"],
  ["choke","窒息"], ["chop","砍；排骨"], ["chopstick","筷子"], ["chorus","合唱"],
  ["Christ","基督"], ["Christian","基督徒"], ["cigar","雪茄"], ["cigarette","香烟"],
  ["cinema","电影院"], ["circle","圆圈；循环"], ["circuit","电路；巡回"], ["circular","圆形的"],
  ["circulate","循环；传播"], ["circumstance","环境；情况"], ["circus","马戏团"], ["citizen","公民"],
  ["civil","公民的；国内的"], ["civilization","文明"], ["claim","声称；要求"], ["clap","鼓掌"],
  ["clarify","澄清"], ["clash","冲突"], ["classic","经典的"], ["classical","古典的"],
  ["classify","分类"], ["clause","条款；从句"], ["claw","爪子"], ["clay","粘土"],
  ["clerk","职员"], ["click","点击"], ["client","客户"], ["cliff","悬崖"],
  ["climate","气候"], ["clinic","诊所"], ["clip","夹子；剪"], ["cloak","斗篷"],
  ["clockwise","顺时针方向的"], ["clone","克隆"], ["cloth","布"], ["clothe","给…穿衣"],
  ["clothing","服装"], ["cloud","云"], ["clown","小丑"], ["club","俱乐部；棍棒"],
  ["clue","线索"], ["clumsy","笨拙的"], ["coach","教练；长途汽车"], ["coal","煤"],
  ["coast","海岸"], ["code","代码；密码"], ["coincidence","巧合"], ["collar","衣领"],
  ["colleague","同事"], ["collection","收藏；收集"], ["college","大学"], ["collision","碰撞"],
  ["colony","殖民地"], ["column","列；专栏"], ["comb","梳子"], ["combine","结合"],
  ["comedy","喜剧"], ["comfort","舒适；安慰"], ["comic","喜剧的"], ["command","命令；指挥"],
  ["commander","指挥官"], ["comment","评论"], ["commerce","商业"], ["commercial","商业的"],
  ["commission","委员会；佣金"], ["commit","犯（罪）；承诺"], ["committee","委员会"],
  ["communicate","交流"], ["communication","交流"], ["communism","共产主义"], ["communist","共产主义者"],
  ["companion","同伴"], ["company","公司；陪伴"], ["compare","比较"], ["comparison","比较"],
  ["compass","指南针"], ["compel","强迫"], ["compensate","补偿"], ["compete","竞争"],
  ["competence","能力"], ["competent","胜任的"], ["competition","竞争；比赛"], ["competitive","有竞争力的"],
  ["competitor","竞争者"], ["complain","抱怨"], ["complaint","抱怨"], ["complete","完整的；完成"],
  ["complex","复杂的"], ["complicated","复杂的"], ["component","成分；组件"], ["compose","组成；作曲"],
  ["composition","作文；作曲"], ["compound","复合物；化合物"], ["comprehension","理解"],
  ["comprehensive","综合的"], ["compress","压缩"], ["comprise","包括"], ["compromise","妥协"],
  ["compulsory","强制性的"], ["compute","计算"], ["computer","电脑"], ["concentrate","集中"],
  ["concentration","集中；浓度"], ["concept","概念"], ["concern","关心；涉及"], ["concert","音乐会"],
  ["conclude","总结；得出结论"], ["conclusion","结论"], ["concrete","具体的；混凝土"],
  ["condemn","谴责"], ["condition","条件；状况"], ["conduct","行为；引导"], ["conductor","指挥；售票员"],
  ["conference","会议"], ["confess","承认；忏悔"], ["confidence","自信；信心"], ["confident","自信的"],
  ["confidential","机密的"], ["confine","限制"], ["confirm","确认"], ["conflict","冲突"],
  ["confront","面对"], ["confuse","使困惑"], ["congratulate","祝贺"], ["congratulation","祝贺"],
  ["congress","国会；代表大会"], ["connect","连接"], ["connection","连接"], ["conscience","良心"],
  ["conscious","有意识的"], ["consensus","共识"], ["consent","同意"], ["consequence","结果"],
  ["consequently","因此"], ["conservation","保护；保存"], ["conservative","保守的"], ["consider","考虑"],
  ["considerable","相当大的"], ["considerate","体贴的"], ["consideration","考虑"], ["consist","由…组成"],
  ["consistent","一致的"], ["constant","不断的；恒定的"], ["constitute","构成"], ["constitution","宪法；构成"],
  ["construct","建造；建设"], ["construction","建设"], ["consult","咨询"], ["consultant","顾问"],
  ["consume","消费"], ["consumer","消费者"], ["consumption","消费"], ["contact","接触；联系"],
  ["contain","包含"], ["container","容器"], ["contemporary","当代的"], ["contend","竞争；主张"],
  ["content","内容；满意的"], ["contest","比赛；竞赛"], ["continent","大陆"], ["continue","继续"],
  ["continuous","连续的"], ["contract","合同"], ["contradict","与…矛盾"], ["contrary","相反的"],
  ["contrast","对比"], ["contribute","贡献；捐献"], ["contribution","贡献"], ["control","控制"],
  ["controversial","有争议的"], ["controversy","争议"], ["convenience","便利"], ["convenient","方便的"],
  ["convention","惯例；大会"], ["conventional","传统的；惯例的"], ["conversation","对话"], ["convert","转换"],
  ["convey","传达；运输"], ["convict","定罪"], ["convince","说服；使确信"], ["cooker","炊具"],
  ["cooperate","合作"], ["cooperation","合作"], ["coordinate","协调"], ["cope","应付"],
  ["copper","铜"], ["copyright","版权"], ["cord","绳子"], ["core","核心"],
  ["cork","软木塞"], ["corn","玉米；谷物"], ["corner","角落"], ["corporation","公司；法人"],
  ["correct","正确的"], ["correction","改正"], ["correspond","对应；通信"], ["correspondent","记者"],
  ["corridor","走廊"], ["corrupt","腐败的"], ["cost","成本；花费"], ["cottage","村舍"],
  ["cotton","棉花"], ["couch","长沙发"], ["cough","咳嗽"], ["council","委员会"],
  ["counsel","建议；律师"], ["count","计数"], ["county","县"], ["couple","夫妇；几个"],
  ["courage","勇气"], ["course","课程；过程"], ["court","法院；球场"], ["courtyard","庭院"],
  ["cousin","表兄弟"], ["cover","覆盖；封面"], ["cow","奶牛"], ["coward","懦夫"],
  ["crack","裂缝；破解"], ["craft","工艺；手艺"], ["crane","起重机；鹤"], ["crash","碰撞；坠毁"],
  ["crawl","爬行"], ["cream","奶油"], ["create","创造"], ["creation","创造"],
  ["creative","创造性的"], ["creature","生物"], ["credit","信用；学分"], ["crew","全体人员"],
  ["crime","罪行"], ["criminal","罪犯"], ["crisis","危机"], ["criterion","标准"],
  ["critic","批评家"], ["critical","批评的；关键的"], ["criticism","批评"], ["criticize","批评"],
  ["crop","庄稼；剪短"], ["cross","穿过；十字架"], ["crossing","十字路口"], ["crowd","人群"],
  ["crown","王冠"], ["crucial","关键的"], ["cruel","残忍的"], ["cruelty","残忍"],
  ["crystal","水晶"], ["cube","立方体"], ["cucumber","黄瓜"], ["cultivate","培养；耕种"],
  ["culture","文化"], ["cunning","狡猾的"], ["cupboard","橱柜"], ["cure","治愈"],
  ["curiosity","好奇心"], ["curious","好奇的"], ["curl","卷曲"], ["currency","货币；流通"],
  ["current","当前的；电流"], ["curriculum","课程"], ["curse","诅咒"], ["curtain","窗帘；幕布"],
  ["cushion","垫子"], ["custom","习俗；海关"], ["customer","顾客"], ["cycle","循环；自行车"],
  ["cyclist","骑自行车的人"], ["daily","每日的"], ["dairy","乳制品"], ["dam","水坝"],
  ["damage","损坏"], ["damp","潮湿的"], ["danger","危险"], ["dangerous","危险的"],
  ["dare","敢"], ["daring","大胆的"], ["data","数据"], ["database","数据库"],
  ["dawn","黎明"], ["daylight","日光"], ["daytime","白天"], ["dazzle","使眼花"],
  ["deadline","截止日期"], ["deadly","致命的"], ["deaf","聋的"], ["deal","交易；处理"],
  ["dear","亲爱的；昂贵的"], ["debate","辩论"], ["debt","债务"], ["decade","十年"],
  ["decay","腐烂"], ["deceive","欺骗"], ["decent","体面的"], ["declaration","宣言"],
  ["decline","下降；拒绝"], ["decorate","装饰"], ["decoration","装饰"], ["decrease","减少"],
  ["dedicate","奉献"], ["deduct","扣除"], ["deed","行为；契约"], ["deepen","加深"],
  ["deer","鹿"], ["defeat","打败"], ["defect","缺陷"], ["defence","防御"],
  ["defend","防御；辩护"], ["define","定义"], ["definite","明确的"], ["definition","定义"],
  ["degree","程度；度；学位"], ["delay","延迟"], ["delegate","代表"], ["delegation","代表团"],
  ["delete","删除"], ["deliberate","故意的"], ["delicate","精致的；微妙的"], ["delight","高兴"],
  ["deliver","递送；发表"], ["delivery","递送"], ["demand","需求；要求"], ["democracy","民主"],
  ["democratic","民主的"], ["demonstrate","示范；证明"], ["denial","否认"], ["denote","表示"],
  ["dense","稠密的"], ["density","密度"], ["dentist","牙医"], ["deny","否认"],
  ["depart","离开"], ["department","部门"], ["departure","离开"], ["depend","依赖"],
  ["dependent","依赖的"], ["deposit","存款；堆积"], ["depress","使沮丧"], ["depression","抑郁；萧条"],
  ["deputy","代表；副手"], ["derive","源自"], ["descend","下降"], ["describe","描述"],
  ["description","描述"], ["desert","沙漠；抛弃"], ["deserve","值得"], ["design","设计"],
  ["designer","设计师"], ["desirable","理想的"], ["desire","渴望"], ["desk","书桌"],
  ["despair","绝望"], ["desperate","绝望的"], ["despite","尽管"], ["destination","目的地"],
  ["destroy","破坏"], ["destruction","破坏"], ["detail","细节"], ["detect","发现；检测"],
  ["detective","侦探"], ["determination","决心"], ["determine","决定"], ["develop","发展；开发"],
  ["development","发展"], ["device","设备；装置"], ["devil","魔鬼"], ["devise","设计；发明"],
  ["devote","奉献"], ["devotion","奉献；热爱"], ["diagram","图表"], ["dial","拨号"],
  ["dialect","方言"], ["dialog","对话"], ["diameter","直径"], ["diamond","钻石"],
  ["diary","日记"], ["dictation","听写"], ["differ","不同"], ["difference","差异"],
  ["digest","消化；文摘"], ["digital","数字的"], ["dignity","尊严"], ["diligent","勤奋的"],
  ["dimension","尺寸；维度"], ["diminish","减少"], ["dine","进餐"], ["dining","用餐"],
  ["diploma","文凭"], ["diplomat","外交官"], ["direct","直接的；指导"], ["direction","方向；指导"],
  ["director","导演；主任"], ["directory","目录；号码簿"], ["dirt","污垢"], ["disable","使无能"],
  ["disabled","残疾的"], ["disadvantage","不利条件"], ["disagree","不同意"], ["disappear","消失"],
  ["disappoint","使失望"], ["disappointment","失望"], ["disaster","灾难"], ["discard","丢弃"],
  ["discharge","排放；解雇"], ["discipline","纪律；学科"], ["disclose","揭露"], ["discount","折扣"],
  ["discourage","使气馁"], ["discover","发现"], ["discovery","发现"], ["discrimination","歧视；辨别"],
  ["discuss","讨论"], ["discussion","讨论"], ["disease","疾病"], ["disgust","厌恶"],
  ["dishonour","耻辱"], ["disk","磁盘"], ["dislike","不喜欢"], ["dismiss","解雇；解散"],
  ["disorder","混乱；失调"], ["display","展示"], ["disposal","处置"], ["dispose","处理；布置"],
  ["dispute","争论"], ["dissolve","溶解；解散"], ["distant","遥远的"], ["distinct","明显的；独特的"],
  ["distinction","区别"], ["distinguish","区分"], ["distribute","分配；分发"], ["distribution","分配；分布"],
  ["district","区；地区"], ["disturb","打扰"], ["disturbing","令人不安的"], ["dive","潜水"],
  ["diverse","多样的"], ["diversion","转移；娱乐"], ["divide","分；除"], ["division","部门；分割"],
  ["divorce","离婚"], ["dizzy","头晕的"], ["dock","码头"], ["document","文件"],
  ["doll","洋娃娃"], ["dolphin","海豚"], ["domestic","国内的；家庭的"], ["dominate","支配；主导"],
  ["donate","捐赠"], ["donation","捐赠"], ["donkey","驴"], ["doom","厄运"],
  ["dormitory","宿舍"], ["dot","点"], ["double","双倍的"], ["doubt","怀疑"],
  ["doubtful","可疑的"], ["downward","向下的"], ["dozen","一打；十二个"], ["draft","草稿；征兵"],
  ["drag","拖；拉"], ["dragon","龙"], ["drain","排水；流干"], ["drama","戏剧"],
  ["dramatic","戏剧性的"], ["draught","气流；穿堂风"], ["drawer","抽屉"], ["dread","恐惧"],
  ["dreadful","可怕的"], ["drift","漂流"], ["drill","钻；训练"], ["drip","滴下"],
  ["drought","干旱"], ["drown","淹死"], ["drowsy","昏昏欲睡的"], ["drug","药物；毒品"],
  ["drum","鼓"], ["drunk","醉的"], ["drunken","醉的"], ["dual","双的"],
  ["due","到期的；应有的"], ["dull","迟钝的；枯燥的"], ["dumb","哑的；沉默的"], ["dump","倾倒；垃圾场"],
  ["durable","耐用的"], ["duration","持续时间"], ["dusk","黄昏"], ["dust","灰尘"],
  ["dusty","布满灰尘的"], ["duty","职责；关税"], ["dwarf","矮子"], ["dye","染料"],
  ["dynamic","动态的；有活力的"], ["dynasty","王朝"], ["eager","渴望的"], ["eagle","鹰"],
  ["earn","赚得"], ["earnest","认真的"], ["earthquake","地震"], ["ease","安逸；减轻"],
  ["eastern","东方的"], ["echo","回声"], ["eclipse","日食；月食"], ["ecology","生态学"],
  ["economy","经济"], ["ecosystem","生态系统"], ["edge","边缘"], ["edible","可食用的"],
  ["edition","版本"], ["editor","编辑"], ["editorial","社论；编辑的"], ["educate","教育"],
  ["education","教育"], ["effect","效果；影响"], ["effective","有效的"], ["efficiency","效率"],
  ["efficient","高效的"], ["effort","努力"], ["elaborate","精心的；详细阐述"], ["elastic","弹性的"],
  ["elbow","肘"], ["elder","年长的"], ["elderly","年迈的"], ["elect","选举"],
  ["election","选举"], ["electric","电的"], ["electrical","与电有关的"], ["electricity","电"],
  ["electron","电子"], ["electronic","电子的"], ["elegant","优雅的"], ["element","元素；成分"],
  ["elementary","初级的；基本的"], ["eliminate","消除"], ["elite","精英"], ["elsewhere","在别处"],
  ["embarrass","使尴尬"], ["embassy","大使馆"], ["embrace","拥抱"], ["emerge","出现；浮现"],
  ["emergency","紧急情况"], ["emission","排放；发射"], ["emit","发射；发出"], ["emotion","情感"],
  ["emotional","情感的"], ["emperor","皇帝"], ["emphasis","强调"], ["emphasize","强调"],
  ["empire","帝国"], ["employ","雇用"], ["employee","雇员"], ["employer","雇主"],
  ["employment","就业；雇用"], ["empress","女皇"], ["enable","使能够"], ["enclose","围住；附上"],
  ["encounter","遭遇；邂逅"], ["encourage","鼓励"], ["encouragement","鼓励"], ["endanger","危及"],
  ["endeavor","努力"], ["ending","结局"], ["endless","无尽的"], ["endure","忍受"],
  ["energetic","精力充沛的"], ["enforce","执行；强制"], ["engage","从事；吸引"], ["engagement","订婚；约会"],
  ["engine","引擎"], ["engineer","工程师"], ["engineering","工程学"], ["enlarge","扩大"],
  ["enormous","巨大的"], ["enquiry","询问"], ["enrich","丰富"], ["enrol","登记；注册"],
  ["ensure","确保"], ["enterprise","企业"], ["entertain","娱乐；款待"], ["entertainment","娱乐"],
  ["enthusiasm","热情"], ["enthusiastic","热情的"], ["entire","整个的"], ["entitle","使有资格"],
  ["entry","进入；条目"], ["envelope","信封"], ["environment","环境"], ["envy","嫉妒"]
];

const high = [...middle, ...highExtra.map(([en,zh])=>({english:en,chinese:zh}))];

// ========== 写入文件 ==========
fs.writeFileSync(path+'/elementary.json', JSON.stringify(ELEM_MAP, null, 2), 'utf8');
fs.writeFileSync(path+'/middle.json', JSON.stringify(middle, null, 2), 'utf8');
fs.writeFileSync(path+'/high.json', JSON.stringify(high, null, 2), 'utf8');

console.log(`小学: ${ELEM_MAP.length} 词`);
console.log(`初中: ${middle.length} 词`);
console.log(`高中: ${high.length} 词`);
console.log('生成完成！');
